export const rightVoice = [
  {
    url: 'asset:/files/excellent.mp3',
    title: 'excellent',
    artist: 'eFlashApps',
    artwork: 'asset:/files/excellent.mp3',
    duration: 5,
  },
  {
    url: 'asset:/files/fantastic.mp3',
    title: 'fantastic',
    artist: 'eFlashApps',
    artwork: 'asset:/files/fantastic.mp3',
    duration: 5,
  },
  {
    url: 'asset:/files/goodanswer.mp3',
    title: 'goodanswer',
    artist: 'eFlashApps',
    artwork: 'asset:/files/goodanswer.mp3',
    duration: 5,
  },
  {
    url: 'asset:/files/goodjob.mp3',
    title: 'soundclick',
    artist: 'eFlashApps',
    artwork: 'asset:/files/goodjob.mp3',
    duration: 5,
  },
  {
    url: 'asset:/files/great.mp3',
    title: 'great',
    artist: 'eFlashApps',
    artwork: 'asset:/files/great.mp3',
    duration: 5,
  },
  {
    url: 'asset:/files/marvelous.mp3',
    title: 'marvelous',
    artist: 'eFlashApps',
    artwork: 'asset:/files/marvelous.mp3',
    duration: 5,
  },
  {
    url: 'asset:/files/sensational.mp3',
    title: 'soundclick',
    artist: 'sensational',
    artwork: 'asset:/files/sensational.mp3',
    duration: 5,
  },
  {
    url: 'asset:/files/spectacular.mp3',
    title: 'spectacular',
    artist: 'eFlashApps',
    artwork: 'asset:/files/spectacular.mp3',
    duration: 5,
  },
];
export const wrongVoice = [
  {
    url: 'asset:/files/uhoh.mp3',
    title: 'specuhohtacular',
    artist: 'eFlashApps',
    artwork: 'asset:/files/uhoh.mp3',
    duration: 5,
  },
  {
    url: 'asset:/files/tryagain.mp3',
    title: 'specuhohtacular',
    artist: 'eFlashApps',
    artwork: 'asset:/files/tryagain.mp3',
    duration: 5,
  },
  {
    url: 'asset:/files/oopsie.mp3',
    title: 'specuhohtacular',
    artist: 'eFlashApps',
    artwork: 'asset:/files/oopsie.mp3',
    duration: 5,
  },
  {
    url: 'asset:/files/youcandoit.mp3',
    title: 'specuhohtacular',
    artist: 'eFlashApps',
    artwork: 'asset:/files/youcandoit.mp3',
    duration: 5,
  },
];
